### PR TITLE
Added ktlint tool to check Kotlin code style

### PR DESCRIPTION
**Pull request by siarhei-luskanau**

### CODE REVIEW

**Comment by ArnyminerZ** [comment]
I guess all the changes in `src` are lint fixes, aren't they? Please, remember to sign the CLA

**Comment by siarhei-luskanau** [comment]
> I guess all the changes in `src` are lint fixes, aren't they? Please, remember to sign the CLA

I have added imports declarations, because ktlint can't safety resolve this.
All "spaces" and "new lines" and "brackets" was changed by using `ktlintFormat` Gradle command.
So developers can save time with code-style by using `ktlintFormat` Gradle command.

**Comment by ArnyminerZ** [comment]
Okey, I guess it makes sense. Let's see what @rfc2822 thinks about this...

Please, remember to sign the CLA, or the PR will not be merged

**Comment by siarhei-luskanau** [comment]
> Unfortunately I have a problem with signing the CLA. I have accepted CLA but nothing is changed.

The problem was the typo in email of commit. I have update the PR with correct email in commit.

**Comment by rfc2822** [comment]
Thanks for your efforts, I think automatic code linting is an interesting idea. However it also adds more things that have to be maintained and that can break while the need for it is not that large at the moment (and we're overwhelmed by other things at the moment). So I'll close this PR.

If your fork contains other meaningful changes, please feel free to open a PR that adds your fork to https://github.com/bitfireAT/dav4jvm/

**Pull request closed without merging**
