### PR TITLE
Port to Java>=9

### PR DESCRIPTION
**Pull request by Raymo111**
Java 9's modules system means xpp3 and thus dav4jvm can't be used. This PR switches the XML pull parser dependency from xpp3 to [ktxml](https://github.com/kobjects/ktxml), which does support Java>=9.

If you do choose to merge this PR, make sure to edit `build.gradle.kts` to point back the GitHub URLs to `bitfireAT`, I had to switch it to `Raymo111` and host it on jitpack myself to test.

### CODE REVIEW

**Comment by rfc2822** [comment]
Hi,

Thanks for the PR. Did you test it on Android / with DAVx⁵? As far as I know, there is no Java 9 support for Android.

**Comment by Raymo111** [comment]
@rfc2822 This doesn't *require* Java 9, it just adds support for it (i.e. for desktop kotlin applications)

**Comment by rfc2822** [comment]
I see, thanks; I'd just like to know how this affects DAVx5, the main reason why we have created dav4jvm for :)

**Comment by Raymo111** [comment]
Yep, I don't think it would affect it in a bad way (since feature parity is still maintained).

**Comment by rfc2822** [comment]
Again thanks for your PR! At the moment, we don't have time to check that and we need to use Java 8 anyway. So I'll close it for now.

But thanks for your pull request and I guess you'll keep the Raymo111 repo anyway, so if we need Java 9 or there's some extra time, we'll have a look there and update this PR.

**Comment by Raymo111** [comment]
Sounds good. Maybe add a note at the bottom of the README linking to the port if you want?

**Comment by rfc2822** [comment]
Would be great. Would it be possible that you create a separate PR for that?

**Pull request closed without merging**
